version: '3.6'
services:
  nginx:
    image: nginx:1.15.10-alpine
    container_name: ${APP_NAME}_nginx
    ports:
      - 80:80
    restart: always
    volumes:
      - ./etc/nginx/app.conf:/etc/nginx/conf.d/app.conf
      - ..:/var/www/html

  postgres:
    image: postgres:11.2-alpine
    container_name: ${APP_NAME}_postgresql
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - 5432:5432
    volumes:
      - ./var/postgresql:/var/lib/postgresql/data

  php:
    build: ./etc/php
    container_name: ${APP_NAME}_php
    restart: always
    ports:
      - 9200:9200
    volumes:
      - ./etc/php/php.ini:/usr/local/etc/php/conf.d/php.ini
      - ..:/var/www/html

  redis:
    image: redis:5.0.4-alpine
    container_name: ${APP_NAME}_redis
    restart: always
    volumes:
      - ./var/redis:/data
